# Generated by Django 5.0.4 on 2024-04-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('display_name', models.CharField(default='display_name', max_length=50)),
                ('skill_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('website_link', models.URLField(default='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='participant_profile_images/')),
                ('facebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('pinterest', models.URLField(default='')),
                ('dribbble', models.URLField(default='')),
                ('behance', models.URLField(default='')),
                ('github', models.URLField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
